In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv('data/car_evaluation.csv')

In [3]:
data.head(10)

  buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc
5  vhigh  vhigh     2       2      med   high   unacc
6  vhigh  vhigh     2       2      big    low   unacc
7  vhigh  vhigh     2       2      big    med   unacc
8  vhigh  vhigh     2       2      big   high   unacc
9  vhigh  vhigh     2       4    small    low   unacc

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
buying      1728 non-null object
maint       1728 non-null object
doors       1728 non-null object
persons     1728 non-null object
lug_boot    1728 non-null object
safety      1728 non-null object
classes     1728 non-null object
dtypes: object(7)
memory usage: 94.6+ KB

In [5]:
data_onehot = data.copy()
data_onehot = pd.get_dummies(data_onehot, columns=['buying'], prefix = ['buying'])

In [6]:
data_onehot.head(10)

,maint,doors,persons,lug_boot,safety,classes,buying_high,buying_low,buying_med,buying_vhigh
0,vhigh,2,2,small,low,unacc,0,0,0,1
1,vhigh,2,2,small,med,unacc,0,0,0,1
2,vhigh,2,2,small,high,unacc,0,0,0,1
3,vhigh,2,2,med,low,unacc,0,0,0,1
4,vhigh,2,2,med,med,unacc,0,0,0,1
5,vhigh,2,2,med,high,unacc,0,0,0,1
6,vhigh,2,2,big,low,unacc,0,0,0,1
7,vhigh,2,2,big,med,unacc,0,0,0,1
8,vhigh,2,2,big,high,unacc,0,0,0,1
9,vhigh,2,4,small,low,unacc,0,0,0,1

In [7]:
# data_onehot['buying'].replace(('vhigh','high','med','low'),(1,2,3,4), inplace=True)
data_onehot['maint'].replace(('vhigh','high','med','low'),(1,2,3,4), inplace=True)
data_onehot['doors'].replace(('2','3','4','5more'),(1,2,3,4), inplace=True)
data_onehot['persons'].replace(('2','4','more'),(1,2,3), inplace=True)
data_onehot['lug_boot'].replace(('small','med','big'),(1,2,3), inplace=True)
data_onehot['safety'].replace(('low','med','high'),(1,2,3), inplace=True)
data_onehot['classes'].replace(('unacc','acc','good','vgood'),(1,2,3,4), inplace=True)

In [8]:
X = data_onehot.drop(['classes'], axis=1)
y = data_onehot['classes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

predictions = knn.predict(X_test)
print(accuracy_score(y_test, predictions) * 100)

92.77456647398844